version: '3.5'
volumes:
  media_portal:

x-healthcheck:
  &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: 3
  start_period: "20s"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  portal-f1:
    container_name: portal-f1
    hostname: portal_f1
    restart: always
    env_file: .env
    build: .
    volumes:
      - media_portal:/staticfiles/uploads
    environment:
      TZ: ${TZ}
      TAMANHO_GROUPED_IMAGES: ${TAMANHO_GROUPED_IMAGES}
    healthcheck:
      <<: *default-healthcheck
      test: pip list
    labels:
      com.mysql.description: "NATURAE Application - NOCS"
      com.mysql.department: "CIDIG"
    logging: *default-logging
    networks:
      - portal
    ports:
      - "8010:5005"

networks:
  portal:
    driver: bridge
    name: Portal_F1
